In [2]:
import torch
import sys

x = torch.rand(2,3) 
y = torch.rand(3,3)
print(x) 
print(y)

tensor([[0.4980, 0.7191, 0.9730],
        [0.7647, 0.4502, 0.2729]])
tensor([[0.0904, 0.9678, 0.4407],
        [0.4092, 0.3452, 0.9711],
        [0.9315, 0.5584, 0.2685]])


In [2]:
x = torch.zeros(5, 3)
print (x.size())
x = torch.tensor([5.5, 3]) 
print (x.size())

torch.Size([5, 3])
torch.Size([2])


In [5]:
x = torch.randn(4, 4) # Returns a tensor filled with random numbers from a normal distribution with mean 0 and variance 1 (also called the standard normal distribution).
y = torch.randn(4, 4)
print(torch.add(x, y))
print(x)
print(x[:, 1])

tensor([[ 1.0174, -1.1082, -1.8664,  1.0388],
        [ 1.6895, -1.1584,  3.1975, -2.0276],
        [-0.6267,  1.5138, -0.2402, -0.7157],
        [-0.4556, -0.2364, -1.9502,  1.8037]])
tensor([[ 0.1796, -0.2688, -1.5333,  1.1461],
        [ 0.4466, -2.3140,  1.4054, -0.3139],
        [-0.8052,  0.9448,  1.1473, -0.5381],
        [-0.6521,  0.3397, -0.3972,  1.0580]])
tensor([-0.2688, -2.3140,  0.9448,  0.3397])


In [7]:
x = torch.randn(6, 4)
# Returns a new tensor with the same data as the self tensor but of a different shape.
# The returned tensor shares the same data and must have the same number of elements, but may have a different size.
y = x.view(3, 8)
z = x.view(-1, 8)
# print(x.size(), y.size(), z.size())
print(x)
print(y)
print(z)

tensor([[-0.8162, -0.5634, -0.6250, -0.5989],
        [-0.9263,  1.1084, -0.6647, -0.6846],
        [-0.6374,  0.7000,  0.8393, -0.0543],
        [ 0.2882,  0.6712,  2.3217, -0.5363],
        [-0.4028, -0.5332, -0.5933, -0.9778],
        [-0.6689, -0.8368,  0.3260, -1.0429]])
tensor([[-0.8162, -0.5634, -0.6250, -0.5989, -0.9263,  1.1084, -0.6647, -0.6846],
        [-0.6374,  0.7000,  0.8393, -0.0543,  0.2882,  0.6712,  2.3217, -0.5363],
        [-0.4028, -0.5332, -0.5933, -0.9778, -0.6689, -0.8368,  0.3260, -1.0429]])
tensor([[-0.8162, -0.5634, -0.6250, -0.5989, -0.9263,  1.1084, -0.6647, -0.6846],
        [-0.6374,  0.7000,  0.8393, -0.0543,  0.2882,  0.6712,  2.3217, -0.5363],
        [-0.4028, -0.5332, -0.5933, -0.9778, -0.6689, -0.8368,  0.3260, -1.0429]])


In [23]:
x = torch.randn(2, 16)
y = x.view(32)
z = x.view(-1, 8)

print(x.size(), y.size(), z.size())

x = torch.randn(2, 3, 4)  # Tensor with shape (2, 3, 4), total elements = 2 * 3 * 4 = 24
y = x.view(-1, 4)         # Reshape x, let PyTorch infer the first dimension
print(x.size(), y.size())

torch.Size([2, 16]) torch.Size([32]) torch.Size([4, 8])
torch.Size([2, 3, 4]) torch.Size([4, 6])


In [10]:
x = torch.randn(1, 4, 32, 24)
y = x.view(8, 2, -1, 3, 8)
print(y.size())
print(y)

# create a 3-dimensional tensor
# of 4 x 5
input_var = torch.randn(3, 4, 5, requires_grad=True)
print(input_var)

torch.Size([8, 2, 8, 3, 8])
tensor([[[[[-8.2960e-01,  2.7725e-01,  5.7931e-01,  ..., -2.2179e-01,
            -1.0469e-01,  7.1539e-01],
           [ 1.5675e-01, -1.2170e+00,  9.1429e-01,  ..., -4.3714e-02,
             3.5849e-01,  2.6986e-01],
           [-1.2317e+00, -4.0013e-01,  1.5213e-01,  ...,  1.5658e+00,
             1.7934e+00, -1.3568e+00]],

          [[-4.2803e-01, -6.7069e-01, -1.0908e-01,  ..., -5.7950e-01,
             2.8716e-02, -2.4445e-01],
           [ 5.7128e-02,  4.2476e-01, -5.3812e-01,  ..., -1.0183e+00,
             1.3357e+00, -1.0609e+00],
           [-7.8355e-01, -6.6227e-01, -9.0689e-01,  ..., -9.4584e-01,
             1.5567e+00,  1.3946e+00]],

          [[-9.9851e-01, -1.8508e+00, -1.1814e+00,  ...,  2.0715e-01,
            -9.1180e-01,  1.9762e-02],
           [-7.2430e-01, -1.3923e-01, -1.1077e+00,  ...,  6.0719e-01,
            -5.7010e-01, -1.0247e+00],
           [ 5.5470e-01,  7.6987e-01, -5.9074e-02,  ..., -7.8234e-01,
             5.4397e-01, -

In [3]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [26]:
mat1=torch.randn(2,3) 
mat2=torch.randn(3,4) 
res=torch.mm(mat1,mat2)
print (res.size(), res)

torch.Size([2, 4]) tensor([[-0.0475, -1.2616, -1.9106, -1.4180],
        [ 0.0943, -0.5951, -4.1377, -3.6981]])


In [18]:
batch1=torch.randn(10,3,4) 
batch2=torch.randn(10,4,5) 
res=torch.bmm(batch1,batch2)
print (res.size())

torch.Size([10, 3, 5])


In [4]:
x = torch.ones(2,2)
y = torch.ones(2,1)
w = torch.randn(2,1,requires_grad=True)
b = torch.randn(1,requires_grad=True)


In [5]:
p = torch.sigmoid(torch.mm(x, w) + b) # prediction
loss = -y*torch.log(p)-(1-y)*torch.log(1-p) # cross-entropy loss
cost = loss.mean() # the cost to minimize

In [6]:
cost.backward()
print (w.grad) 
print (b.grad)

tensor([[-0.7051],
        [-0.7051]])
tensor([-0.7051])


In [22]:
print(w)
print (b)

tensor([[-0.2773],
        [ 1.6396]], requires_grad=True)
tensor([1.0437], requires_grad=True)


In [28]:
import torch
import torch.nn as nn
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 3x3 square convolution kernel
        self.conv1 = nn.Conv2d(3, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        self.pool = nn.MaxPool2d(2, 2)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 6 * 6, 120)  # 6*6 from image dimension
        self.fc2 = nn.Linear(120, 84) 
        self.fc3 = nn.Linear(84, 10)
        
    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = self.pool(torch.relu(self.conv1(x)))
        # If the size is a square you can only specify a single number
        x = self.pool(torch.relu(self.conv2(x)))
        x = x.view(-1, self.num_flat_features(x))
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    def num_flat_features(self, x):
        size = x.size()[1:] # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features
    
print('Class Net defined')

Class Net defined


In [29]:
import torchvision
import torchvision.transforms as transforms

In [30]:
# transforms.Compose: Combines multiple image transformations.
# ToTensor() -> PIL image or Numpy array to TF array
# Normalize() -> Normalizes the image's pixel values. In this case, 
#   the mean is (0.5, 0.5, 0.5) and the standard deviation is (0.5, 0.5, 0.5) 
#   for each RGB channel
transform = transforms.Compose(
    [transforms.ToTensor(), transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))]
)
trainset = torchvision.datasets.CIFAR10(
    root="./data", train=True, download=True, transform=transform
)
trainloader = torch.utils.data.DataLoader(
    trainset, batch_size=4, shuffle=True, num_workers=2
)

100%|██████████| 170498071/170498071 [00:48<00:00, 3481072.06it/s]


Extracting ./data/cifar-10-python.tar.gz to ./data


In [32]:
testset = torchvision.datasets.CIFAR10(root='./data', train=False, download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=4, shuffle=False, num_workers=2)

Files already downloaded and verified


In [33]:
import torch.optim as optim

net = Net()
# This is the loss function (cross-entropy) commonly used for classification tasks. 
# It measures the difference between the predicted class probabilities and the true labels.
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)


for epoch in range(1):
    # loop over the dataset multiple times
    running_loss = 0.0
    for i, data in enumerate(trainloader, 0):
        # training code for each batch
        # get the inputs;
        inputs, labels = data
        # forward + backward + optimize
        outputs = net(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()  # Does the update
        # print statistics
        running_loss += loss.item()
        if i % 2000 == 1999:  # every 2000 batches
            print("[%d, %5d] loss: %.3f" % (epoch + 1, i + 1, running_loss / 2000))
            running_loss = 0.0
print("Finished Training")

[1,  2000] loss: 49.727
[1,  4000] loss: 90.079
[1,  6000] loss: 182.489
[1,  8000] loss: 305.459
[1, 10000] loss: 361.597
[1, 12000] loss: 502.522
Finished Training


In [35]:
correct = 0
total = 0
#with torch.no_grad():
for data in testloader:
    images, labels = data
    outputs = net(images)
    _, predicted = torch.max(outputs.data, 1)
    total += labels.size(0)
    correct += (predicted == labels).sum().item()

print(f'Accuracy of the network on the 10,000 test images: {100 * correct / total:.2f}%')



Accuracy of the network on the 10,000 test images: 10.00%
